### ISSUE TITLE
对于分页列表为多页和内容多页的小说站，该如何编写抓取方式

### ISSUE THREAD

**Issue by saobee** [yinyue200/FlyReaderExtensions#1]
比如：https://www.szhswy.com/85224.html 这样的

**Comment by yinyue200** [comment]
你可以在你的代码中定义一个额外的函数`getChapterListRESET`。当你在抓取分页列表时发现仍有后续内容需要加载时，你需要自行保存好上下文数据，然后抛出一个异常对象，这个异常对象必须有`type`和`helpLink`属性，其中`type`的值需为`reset`。之后阅读器将试图从`helpLink`所指示的链接中爬取内容，爬取完成后将调用`getChapterListRESET`，`getChapterListRESET`的函数签名与`getChapterList`一致。如果仍未加载完所需数据，您也可以选择在`getChapterListRESET`中继续抛出错误。

**Comment by saobee** [comment]
谢谢回答，在remen2019.yfb这个示例文件里面看到了示例
